### ISSUE TITLE
dependency-check-gradle does not work on JDK 11.0.8 (NoSuchMethodError JsonParser.getReadCapabilities)

### ISSUE THREAD

**Issue by wbervoets** [dependency-check/dependency-check-gradle#220]
When running dependency-check-gradle on JDK11.0.8 or later I get the following exceptions when running dependencyCheckAnalyze:

java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;
org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:298)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)

Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;
        at com.fasterxml.jackson.databind.DeserializationContext.<init>(DeserializationContext.java:211)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.<init>(DefaultDeserializationContext.java:50)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.<init>(DefaultDeserializationContext.java:391)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.createInstance(DefaultDeserializationContext.java:413)
        at com.fasterxml.jackson.databind.ObjectReader.createDeserializationContext(ObjectReader.java:2245)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1996)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1174)
        at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:96)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more

My setup:
- Gradle 7.0.2
- Android Gradle plugin 4.2.1
- JDK 11 or later
- Windows or MacOS

in my app build.gradle.kts I define:

```
plugins {
     id("org.owasp.dependencycheck") version "6.2.0"
}
```

```
dependencyCheck {
    analyzers.assemblyEnabled = false
    scanProjects = listOf(":app")
    val skipConfigs = configurations.filter { configuration ->
        configuration.name.contains("ktlint") ||
                configuration.name.contains("lintClassPath")
    }.map {
        it.name
    }.toMutableList()
    skipConfigs.add("Business:ktlint")

    println("Skipped Configs: $skipConfigs")
    skipConfigurations = skipConfigs

    suppressionFile = "app/config/owasp/owasp-suppressions.xml"
}
```

Removing skipConfigurations, suppressionFile and scanProjects does not make a difference.
Running dependencyCheckPurge does not make a difference.

A few other things I'm not fully understanding as a new user of the plugin:
- dependencyCheckAnalyze versus dependencyCheckAggregate => don't understand the difference
- I believe dependencyCheckAggregate just hangs on Windows (does complete on MacOS though)
- I don't want vulnerabilities reported in ktlint gradle plugin because it includes an old Kotlin version. As this code is never packaged in the final Android APK/AAB => have not been able to suppress this.

**Comment by wbervoets** [comment]
When moving everything to the root build.gradle.kts I do not get the above exception. dependencyCheckAnalyze then returns no vulnerabilities found.

dependencyCheckAggregate does report a set of vulnerabilities.

**Comment by wbervoets** [comment]
Is this plugin being actively developed?

**Comment by Lucas3oo** [comment]
Your issue looks similar to #3380
In some way the classapth of the plugin gets mixed-up so another version of Jackson is used.

**Comment by Lucas3oo** [comment]
Check if you have some dependency in e.g. buildSrc/build.gradle that in turn depends on an old Jackson version. 
Dependencies in buildSrc/build.gradle will not as far as I understand show up when executing ./gradlew buildEnvironment
